export const siteConfig = {
    name: "Prospera Hospitality",
    name1:"Prospera",
    name2:"Hospitality",
    logoname: "Prospera",
    description: "Make beautiful websites regardless of your design experience.",
    favicon: "@/app/favicon.ico",
    ownername: "Kamini Singh",
    phoneNumber: "7021719016",
    companyname: "Prospera Hospitality Pvt. Ltd.",
    link: "https://www.prosperaahospitality.com/",
    email: "sales@prosperaahospitality.com",
    address: "Office no 1204, The Affaires Palm Paradise, Plam Beach Rd, Sector 17, Sanpada, Navi Mumbai, Maharashtra 400 705",
    telephone: ["7021719016", "8928122610"],
    AboutUs: "About Us",
    OurServices: "Our Services",
    Pricing: "Pricing",
    SuccessStories: "Success Stories",
    VacationRental: "Vacation Rental",
    ContactUs: "Contact Us",
    Careers: "Careers",
    Blog: "Blog",
    HotelRevenueManagement: "Hotel Revenue Management",
    HotelDigitalBrandBuilding: "Hotel Digital Brand Building",
    HotelSocialMediaMarketing: "Hotel Social Media Marketing",
    HotelOnlineReputationMangment: "Hotel Online Reputation Mangment",
    HotelVirtualFrontOffice: "Hotel Virtual Front Office",
    HotelWebsiteDevelopment: "Hotel Website Development",
    HotelOTAManagment: "Hotel OTA Managment",
    HotelPhotoshootVideoMaking: "Hotel Photoshoot & Video Making",
    HotelSEO: "Hotel SEO",
    HotelChannelManager: "Hotel Channel Manager",
    HotelContentMarketing: "Hotel Content Marketing",
    HotelPropertyManagementSystem: "Hotel Property Management System",
    TermsConditions: "Terms & Conditions",
    PrivacyPolicy: "Privacy Policy",
    RefundPolicy: "Refund Policy",
  
    keywords: [
      "Prospera",
      "Prospera Hospitality",
      "Prospera Hospitality Pvt. Ltd.",
      "Hospitality Company",
      "Website Development",
      "Best Website Development Company",
      "hotel revenue management services",
      "revenue optimization for hotels",
      "hotel revenue strategy",
      "maximize hotel revenue",
      "yield management for hotels",
      "revenue management software for hotels",
      "hotel booking optimization",
      "online travel agency connections",
      "hotel booking integration",
      "OTA management services",
      "connect hotel with MakeMyTrip",
      "Agoda hotel booking integration",
      "OTA channel management",
      "Expedia hotel connection",
      "connect hotel with Booking.com",
      "OTAs for hotels in India",
      "hotel distribution channels",
      "OTA rate management",
      "OTA booking solutions",
      "hotel bookings via OTAs",
      "hotel property management system",
      "PMS for hotel industry",
      "hotel software solutions",
      "PMS software integration",
      "hotel management software",
      "cloud-based PMS for hotels",
      "PMS features for hotels",
      "hotel front desk software",
      "hotel operations management",
      "hospitality management system",
      "hotel restaurant management software",
      "restaurant POS system for hotels",
      "hotel dining management",
      "restaurant reservation system",
      "hotel F&B management software",
      "hotel kitchen management system",
      "restaurant inventory management",
      "hotel menu management system",
      "hotel catering software",
      "hotel bar management software",
      "hotel channel manager software",
      "OTA channel manager integration",
      "multi-channel hotel management",
      "channel manager for hotels",
      "hotel rate manager",
      "online distribution channel manager",
      "hotel inventory management software",
      "channel manager system",
      "channel manager for small hotels",
      "hotel rate distribution system",
      "hotel website design services",
      "custom hotel website development",
      "hotel website optimization",
      "SEO for hotel websites",
      "responsive hotel website",
      "mobile-friendly hotel website",
      "hotel booking website",
      "website for boutique hotels",
      "hotel website maintenance",
      "hotel website upgrade",
      "hotel revenue management India",
      "PMS software India",
      "restaurant management system India",
      "channel manager India",
      "hotel website design India",
      "OTA integration India",
      "hotel software solutions India",
      "hotel technology India",
      "hotel tech solutions India",
      "hospitality software India",
      "hotel booking engine development",
      "direct booking for hotels",
      "hotel booking system integration",
      "hotel room rate management",
      "hotel online marketing",
      "hotel digital solutions",
      "hospitality technology solutions",
      "hotel software development company",
      "hotel tech support services",
      "hotel software consultancy",
      "hospitality technology trends",
      "hotel industry software solutions",
      "hotel tech innovations",
      "hospitality software providers",
      "hotel tech industry",
      "hospitality technology services",
      "hotel software experts",
      "hotel tech consultancy",
      "hotel technology providers",
      "hotel technology solutions",
      "hotel PMS features",
      "restaurant management software features",
      "channel manager benefits",
      "hotel website features",
      "OTA integration benefits",
      "hotel booking engine benefits",
      "hotel software customization",
      "hotel software security",
      "cloud-based hotel solutions",
      "mobile app for hotels",
      "AI in hotel industry",
      "machine learning for hotels",
      "big data in hospitality",
      "cloud computing for hotels",
      "IoT in hotel management",
      "digital transformation in hospitality",
      "blockchain in hotel industry",
      "cybersecurity for hotels",
      "data analytics for hotels",
      "technology-driven hospitality",
      "hotel revenue management company",
      "PMS software provider",
      "restaurant management system developer",
      "channel manager software vendor",
      "hotel website developer",
      "OTA integration service provider",
      "hospitality software company",
      "hotel technology consultancy",
      "hotel tech solution provider",
      "hotel software innovation",
      "hotel technology partner",
      "hospitality software solutions provider",
      "hotel tech strategy",
      "hotel tech implementation",
      "hotel software project management",
      "hotel tech integration services",
      "hotel tech upgrade",
      "hospitality IT solutions",
      "hotel tech infrastructure",
      "hotel tech development",
      "technology solutions for hotels",
      "hotel tech services for small hotels",
      "tech solutions for boutique hotels",
      "hotel tech for independent hotels",
      "technology for luxury hotels",
      "tech solutions for budget hotels",
      "hotel tech for chain hotels",
      "hotel tech for resort properties",
      "technology for serviced apartments",
      "tech solutions for hostels",
      "best hotel revenue management strategies",
      "affordable PMS software for hotels",
      "top-rated restaurant POS system",
      "how to integrate channel manager",
      "benefits of custom hotel website",
      "features of cloud-based PMS",
      "importance of OTA integration",
      "advantages of AI in hospitality",
      "tips for hotel digital marketing",
      "cost-effective hotel technology solutions",
      "Navi Mumbai hotel technology services",
      "Maharashtra hotel software solutions",
      "Mumbai hospitality tech providers",
      "Vashi hotel tech consultancy",
      "Panvel hotel software developers",
      "Thane hotel technology experts",
      "Pune hospitality software solutions",
      "Goa hotel tech providers",
      "Western India hotel technology",
      "hotel tech support in India"
    ],
  
    navItems: [
      {
        label: "Home",
        href: "/",
      },
      {
        label: "About Us",
        href: "/about-us",
      },
      {
        label: "Our Services",
        href: "/our-services",
      },
      {
        label: "Pricing",
        href: "/pricing",
      },
      {
        label: "Testimonials",
        href: "/testimonials",
      },
      {
        label: "Vacation Rental",
        href: "/vacation-rental",
      },
      {
        label: "Contact Us",
        href: "/contact-us",
      },
      {
        label: "Careers",
        href: "/careers",
      },
      {
        label: "Blog",
        href: "/blog",
      },
    ],
  
    adminNavItems: [
      // {
      //   label: "Dashboard",
      //   href: "/admin/dashboard",
      // },
      {
        label: "Blog",
        href: "/admin/blog",
      },
      {
        label: "Careers",
        href: "/admin/careers",
      },
    ],
  
    ServicesItems: [
      {
        label: "Hotel Revenue Management",
        href: "/services/Hotel-Revenue-Management",
      },
      {
        label: "Hotel Digital Brand Building",
        href: "/services/Hotel-Digital-Brand-Building",
      },
      {
        label: "Hotel Social Media Marketing",
        href: "/services/Hotel-Social-Media-Marketing",
      },
      {
        label: "Hotel Online Reputation Mangment",
        href: "/services/Hotel-Online-Reputation-Mangment",
      },
      {
        label: "Hotel Virtual Front Office",
        href: "/services/Hotel-Virtual-Front-Office",
      },
      {
        label: "Hotel Website Development",
        href: "/services/Hotel-Website-Development",
      },
      {
        label: "Hotel OTA Managment",
        href: "/services/Hotel-OTA-Managment",
      },
      {
        label: "Hotel Photoshoot & Video Making",
        href: "/services/Hotel-Photoshoot-Video-Making",
      },
      {
        label: "Hotel SEO",
        href: "/services/Hotel-SEO",
      },
      {
        label: "Hotel Channel Manager",
        href: "/services/Hotel-Channel-Manager",
      },
      {
        label: "Hotel Content Marketing",
        href: "/services/Hotel-Content-Marketing",
      },
      {
        label: "Hotel Property Management System",
        href: "/services/Hotel-Property-Management-System",
      },
    ],
  
    PoliciesItems: [
      {
        label: "Terms & Conditions",
        href: "/tearms-and-conditions",
      },
      {
        label: "Privacy Policy",
        href: "/policies/privacy-policy",
      },
      {
        label: "Refund Policy",
        href: "/policies/refund-policy",
      },
    ],
  
    links: {
      facebook: "https://www.facebook.com/profile.php?id=61562089264990&mibextid=ZbWKwL",
      instagram: "https://www.instagram.com/prosperahospitality/",
      twitter: "https://twitter.com/",
      linkdin: "https://www.linkedin.com/company/prosperaa-hospitality",
      github: "https://github.com/prosperahospitality",
    },
  };
  